"""Generate original paper figures from PR-MaGIC experiment files.

This script intentionally does not load, copy, or reference any pre-existing
image asset.  All framework graphics are drawn from Matplotlib patches
and text.  The empirical plots are computed from the candidate-level and
risk--coverage CSV files produced by the experiments.

Outputs:

    figures/generated/candidate_instability.pdf/.png
    figures/generated/risk_coverage_all_generators.pdf/.png

The framework overview and graphical abstract are maintained as declarative
cvpr-figure specs under figures/generated/specs/ and rendered to files whose
names start with ``cvpr_``.  They are deliberately not regenerated by this
Matplotlib script.

The framework and graphical-abstract figures contain no third-party artwork.
The candidate-instability figure uses one high-regret replay episode from
each of FSS-1000, COCO-20i, and Pascal-5i only as an illustrative diagnostic;
it is not used to compute any aggregate result.
"""

from __future__ import annotations

import csv
import math
import os
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Polygon, Rectangle


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "figures" / "generated"
ALPHA = 0.25
BETA = 0.10


def setup_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "DejaVu Serif"],
            "font.size": 10,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 8,
            "axes.linewidth": 0.8,
            "figure.dpi": 150,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
        }
    )


def save_figure(fig: plt.Figure, stem: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    audit_dir = os.environ.get("NATURE_FIGURE_AUDIT_SCRIPTS")
    if audit_dir:
        sys.path.insert(0, audit_dir)
        from audit_panel_alignment import require_matplotlib_panel_alignment

        qa_dir = OUT / "qa"
        qa_dir.mkdir(parents=True, exist_ok=True)
        require_matplotlib_panel_alignment(
            fig,
            json_out=qa_dir / f"{stem}.alignment.json",
            overlay_svg=qa_dir / f"{stem}.alignment.svg",
            strict=True,
        )
    fig.savefig(OUT / f"{stem}.png", dpi=600, bbox_inches="tight", facecolor="white")
    fig.savefig(OUT / f"{stem}.pdf", bbox_inches="tight", facecolor="white")
    fig.savefig(OUT / f"{stem}.svg", bbox_inches="tight", facecolor="white")
    plt.close(fig)


def rounded_box(ax, xy, width, height, text, *, face="#f7fafc", edge="#29465b",
                fontsize=10, weight="normal", radius=0.03, text_color="#17202a"):
    x, y = xy
    patch = FancyBboxPatch(
        (x, y), width, height,
        boxstyle=f"round,pad=0.012,rounding_size={radius}",
        linewidth=1.3,
        edgecolor=edge,
        facecolor=face,
    )
    ax.add_patch(patch)
    ax.text(
        x + width / 2,
        y + height / 2,
        text,
        ha="center",
        va="center",
        fontsize=fontsize,
        fontweight=weight,
        color=text_color,
        linespacing=1.25,
    )
    return patch


def arrow(ax, start, end, *, color="#536878", lw=1.4, style="-|>", mutation=13,
          connectionstyle="arc3,rad=0"):
    ax.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle=style,
            mutation_scale=mutation,
            linewidth=lw,
            color=color,
            connectionstyle=connectionstyle,
        )
    )


def abstract_tile(ax, x, y, width, height, label, *, color="#d8e6ef",
                  accent="#8bb5ce", mask=False):
    ax.add_patch(
        FancyBboxPatch(
            (x, y), width, height,
            boxstyle="round,pad=0.008,rounding_size=0.02",
            linewidth=0.9,
            edgecolor="#38546b",
            facecolor=color,
        )
    )
    if mask:
        # An abstract binary-mask silhouette made only from geometric patches.
        ax.add_patch(Polygon(
            [
                (x + 0.32 * width, y + 0.17 * height),
                (x + 0.57 * width, y + 0.20 * height),
                (x + 0.70 * width, y + 0.43 * height),
                (x + 0.60 * width, y + 0.78 * height),
                (x + 0.39 * width, y + 0.84 * height),
                (x + 0.23 * width, y + 0.60 * height),
            ],
            closed=True,
            facecolor=accent,
            edgecolor="none",
            alpha=0.95,
        ))
    else:
        # An intentionally abstract feature/image tile; it is not copied from
        # a dataset or paper image.
        ax.add_patch(Polygon(
            [
                (x + 0.08 * width, y + 0.18 * height),
                (x + 0.36 * width, y + 0.33 * height),
                (x + 0.54 * width, y + 0.16 * height),
                (x + 0.90 * width, y + 0.58 * height),
                (x + 0.79 * width, y + 0.88 * height),
                (x + 0.12 * width, y + 0.78 * height),
            ],
            closed=True,
            facecolor=accent,
            edgecolor="none",
            alpha=0.85,
        ))
        ax.plot(
            [x + 0.08 * width, x + 0.36 * width, x + 0.54 * width, x + 0.90 * width],
            [y + 0.70 * height, y + 0.45 * height, y + 0.63 * height, y + 0.30 * height],
            color="#ffffff",
            linewidth=1.0,
            alpha=0.85,
        )
    ax.text(x + width / 2, y - 0.055, label, ha="center", va="top", fontsize=8)


def draw_framework_overview() -> None:
    fig, ax = plt.subplots(figsize=(15.5, 5.2))
    ax.set_xlim(0, 15.5)
    ax.set_ylim(0, 5.2)
    ax.axis("off")

    # Section boundaries.
    sections = [
        (0.15, 0.35, 3.0, 4.45, "1  Reference-conditioned input", "#edf5fa"),
        (3.35, 0.35, 3.35, 4.45, "2  Training-free generation", "#f4f8ee"),
        (6.90, 0.35, 3.35, 4.45, "3  Candidate ranking", "#fff8ea"),
        (10.45, 0.35, 4.90, 4.45, "4  Baseline-relative acceptance", "#f8eff7"),
    ]
    for x, y, w, h, title, face in sections:
        rounded_box(ax, (x, y), w, h, "", face=face, edge="#72818c", radius=0.08)
        ax.text(x + w / 2, y + h - 0.25, title, ha="center", va="top",
                fontsize=10, fontweight="bold", color="#23313d")

    abstract_tile(ax, 0.48, 2.78, 1.05, 1.08, "support image", color="#dbeaf3", accent="#9fc4d7")
    abstract_tile(ax, 0.48, 1.14, 1.05, 1.08, "support mask", color="#e3f1e4", accent="#78b98a", mask=True)
    abstract_tile(ax, 1.80, 2.00, 1.05, 1.08, "query image", color="#f1e4da", accent="#d7a77c")
    ax.text(1.52, 0.72, r"$(I_s,Y_s,I_q)$", ha="center", va="center", fontsize=11)

    rounded_box(ax, (3.72, 2.50), 1.25, 0.72, "Frozen\nencoder", face="#ffffff", edge="#457b9d", weight="bold")
    rounded_box(ax, (5.25, 2.50), 1.12, 0.72, r"$z_s,z_q$" + "\n" + "features", face="#ffffff", edge="#457b9d")
    arrow(ax, (2.92, 2.53), (3.70, 2.86), color="#457b9d")
    arrow(ax, (4.98, 2.86), (5.23, 2.86), color="#457b9d")
    ax.text(5.28, 1.72, r"$F_q^{(t+1)}=F_q^{(t)}+\eta V^{(t)}+\sqrt{2\eta}\,\xi^{(t)}$",
            ha="center", va="center", fontsize=8.5,
            bbox=dict(boxstyle="round,pad=0.35", facecolor="#e0f0e5", edgecolor="#699b78"))
    ax.text(5.28, 1.15, r"$\{M_0,M_1,\ldots,M_T\}$", ha="center", va="center",
            fontsize=12, fontweight="bold", color="#315b42")
    arrow(ax, (5.80, 2.48), (5.80, 1.96), color="#699b78")
    arrow(ax, (5.38, 1.25), (4.15, 1.25), color="#699b78", connectionstyle="arc3,rad=0.25")
    ax.text(4.12, 1.08, "iterative mask-decoder\nrefinement", ha="center", va="top", fontsize=8)

    rounded_box(ax, (7.28, 2.67), 2.55, 0.98,
                r"$S_{\mathrm{orig}}(t)=q_{\mathrm{sup}}(t)$" + "\n" +
                r"$+0.25q_{\mathrm{dec}}(t)+0.10q_{\mathrm{fg}}(t)$",
                face="#fffdf7", edge="#c58b3b", fontsize=9)
    ax.text(8.55, 1.92, r"$t^*=\arg\max_t S_{\mathrm{orig}}(t)$", ha="center", va="center",
            fontsize=11, fontweight="bold", color="#7a531c")
    ax.text(8.55, 1.30, "proposal may be better or worse\nthan baseline $M_0$", ha="center", va="center",
            fontsize=8.5, color="#7a531c")
    arrow(ax, (6.68, 2.86), (7.25, 3.12), color="#c58b3b")

    rounded_box(ax, (10.82, 2.76), 1.55, 0.80,
                r"$\Delta q_{\mathrm{sup}}\geq0$" + "\n" +
                r"$\Delta q_{\mathrm{fg}}\geq0$?",
                face="#fff5fb", edge="#9b4f86", fontsize=10, weight="bold")
    arrow(ax, (9.86, 3.15), (10.79, 3.15), color="#9b4f86")
    rounded_box(ax, (12.85, 3.12), 1.05, 0.62, "accept\n$M_{t^*}$", face="#e4f2e5", edge="#4c956c", weight="bold")
    rounded_box(ax, (12.85, 1.70), 1.05, 0.62, "fallback\n$M_0$", face="#fbe4e4", edge="#b85c5c", weight="bold")
    arrow(ax, (12.39, 3.18), (12.82, 3.42), color="#4c956c")
    arrow(ax, (12.39, 3.05), (12.82, 2.02), color="#b85c5c")
    ax.text(12.58, 3.57, "yes", fontsize=8, color="#4c956c")
    ax.text(12.52, 2.42, "no", fontsize=8, color="#b85c5c")
    rounded_box(ax, (14.25, 2.40), 0.83, 0.92, "final\nmask", face="#e9eef8", edge="#526aa3", weight="bold")
    arrow(ax, (13.93, 3.42), (14.22, 2.95), color="#526aa3")
    arrow(ax, (13.93, 2.02), (14.22, 2.76), color="#526aa3")

    ax.text(7.75, 0.53,
            "No query ground truth is used by the generator, selector, or gate; it is used only for evaluation.",
            ha="center", va="center", fontsize=9, color="#4c5964",
            bbox=dict(boxstyle="round,pad=0.25", facecolor="white", edgecolor="#b9c2c8"))
    save_figure(fig, "framework_overview")


def draw_graphical_abstract() -> None:
    fig, ax = plt.subplots(figsize=(13.0, 4.1))
    ax.set_xlim(0, 13)
    ax.set_ylim(0, 4.1)
    ax.axis("off")
    ax.text(6.5, 3.83, "Guarded PR-MaGIC: baseline-relative candidate selection", ha="center", va="center",
            fontsize=15, fontweight="bold", color="#1c2833")

    blocks = [
        (0.30, 0.85, 2.35, 2.30, "Candidate pool", "", "#edf5fa", "#457b9d"),
        (3.20, 0.85, 2.35, 2.30, "Original selector", r"$S_{orig}(t)$" + "\n" + "produces proposal" + "\n" + r"$t^*$", "#fff8ea", "#c58b3b"),
        (6.10, 0.85, 2.65, 2.30, "Baseline-relative gate", r"$\Delta q_{sup}\geq0$" + "\n" + r"and $\Delta q_{fg}\geq0$", "#f8eff7", "#9b4f86"),
        (9.30, 0.85, 3.35, 2.30, "Reliable output", "", "#eef7ef", "#4c956c"),
    ]
    for x, y, w, h, title, body, face, edge in blocks:
        rounded_box(ax, (x, y), w, h, "", face=face, edge=edge, radius=0.08)
        ax.text(x + w / 2, y + h - 0.33, title, ha="center", va="top", fontsize=11, fontweight="bold", color=edge)
        if body:
            ax.text(x + w / 2, y + h / 2 - 0.05, body, ha="center", va="center", fontsize=11, color="#26343f")
    # Abstract candidate strips.
    for k in range(6):
        x = 0.60 + 0.30 * k
        ax.add_patch(Rectangle((x, 1.25 + 0.045 * k), 0.22, 0.72, facecolor="#7ca9c1" if k == 0 else "#c2d9e4",
                               edgecolor="#38546b", linewidth=0.6))
    ax.text(1.48, 2.52, "six masks from\ntraining-free refinement", ha="center", va="center", fontsize=10, color="#26343f")
    ax.text(1.48, 1.07, r"$M_0,M_1,\ldots,M_T$", ha="center", fontsize=9)
    # Gate branches; these are schematic boxes, not imported mask artwork.
    ax.add_patch(Rectangle((10.00, 1.25), 0.72, 1.45, facecolor="#d9ecd9", edgecolor="#4c956c", linewidth=1.0))
    ax.text(10.36, 1.98, "accept\nrefinement", ha="center", va="center", fontsize=9, color="#39704f")
    ax.add_patch(Rectangle((10.82, 2.19), 1.25, 0.45, facecolor="#d9ecd9", edgecolor="#4c956c", linewidth=0.8))
    ax.add_patch(Rectangle((10.82, 1.46), 1.25, 0.45, facecolor="#f7dddd", edgecolor="#b85c5c", linewidth=0.8))
    ax.text(11.45, 2.41, r"$M_{t^*}$", ha="center", va="center", fontsize=11, fontweight="bold")
    ax.text(11.45, 1.68, r"$M_0$", ha="center", va="center", fontsize=11, fontweight="bold")
    for x1, x2, color in [(2.67, 3.15, "#65747e"), (5.57, 6.05, "#65747e"), (8.77, 9.25, "#65747e")]:
        arrow(ax, (x1, 2.00), (x2, 2.00), color=color, lw=1.6)
    ax.text(6.5, 0.42,
            "training-free  ·  selective prediction  ·  cross-generator transfer",
            ha="center", va="center", fontsize=10, color="#46545f")
    save_figure(fig, "graphical_abstract")


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def choose_representative(path: Path) -> dict[str, object]:
    rows = read_csv_rows(path)
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[row["obj_name"]].append(row)
    candidates: list[dict[str, object]] = []
    for obj_name, group in groups.items():
        group.sort(key=lambda row: int(row["iteration"]))
        score = [
            float(row["support_query"])
            + ALPHA * float(row["decoder_confidence"])
            + BETA * float(row["foreground_background_separation"])
            for row in group
        ]
        proposal_index = max(range(len(group)), key=lambda index: score[index])
        oracle_index = max(range(len(group)), key=lambda index: float(group[index]["miou"]))
        baseline = group[0]
        proposal = group[proposal_index]
        gate_accepts = (
            proposal_index == 0
            or (
                float(proposal["support_query"]) >= float(baseline["support_query"])
                and float(proposal["foreground_background_separation"])
                >= float(baseline["foreground_background_separation"])
            )
        )
        proposal_delta = float(proposal["miou"]) - float(baseline["miou"])
        oracle_gap = float(group[oracle_index]["miou"]) - float(proposal["miou"])
        margin = min(
            float(proposal["support_query"]) - float(baseline["support_query"]),
            float(proposal["foreground_background_separation"])
            - float(baseline["foreground_background_separation"]),
        ) if proposal_index != 0 else math.inf
        # Prefer a clearly degraded original proposal rejected by the gate and
        # with a large selector regret. Fall back to the largest regret if a
        # benchmark has no such episode in the selected source file.
        candidates.append(
            {
                "obj_name": obj_name,
                "group": group,
                "scores": score,
                "proposal_index": proposal_index,
                "oracle_index": oracle_index,
                "proposal_delta": proposal_delta,
                "oracle_gap": oracle_gap,
                "gate_accepts": gate_accepts,
                "margin": margin,
                "preferred": bool(proposal_delta < -1e-12 and not gate_accepts),
            }
        )
    candidates.sort(key=lambda item: (item["preferred"], item["oracle_gap"]), reverse=True)
    return candidates[0]


def draw_candidate_instability() -> None:
    specs = [
        ("FSS-1000", ROOT / "results/multicriteria/fss_f0_s42_full/0/csvs/selector_original_candidates.csv"),
        ("COCO-20i", ROOT / "results/multicriteria/coco_f0_s45_heldout1000/0/csvs/selector_original_candidates.csv"),
        ("Pascal-5i", ROOT / "results/multicriteria/pascal_f0_s45_full1000_fixed2/0/csvs/selector_original_candidates.csv"),
    ]
    chosen = [(benchmark, choose_representative(path)) for benchmark, path in specs]

    fig, axes = plt.subplots(1, 3, figsize=(15.0, 4.15), constrained_layout=True)
    for ax, (benchmark, item) in zip(axes, chosen):
        group = item["group"]
        iterations = [int(row["iteration"]) for row in group]
        mious = [float(row["miou"]) for row in group]
        scores = item["scores"]
        score_min = min(scores)
        score_max = max(scores)
        if score_max > score_min:
            score_norm = [0.55 + 0.35 * (value - score_min) / (score_max - score_min) for value in scores]
        else:
            score_norm = [0.72 for _ in scores]
        ax.plot(iterations, mious, color="#1d5f85", marker="o", linewidth=2.0, label="candidate mIoU")
        ax.plot(iterations, score_norm, color="#c56b2f", marker="s", linestyle="--", linewidth=1.5,
                label="normalized selector score")
        proposal_iter = int(group[item["proposal_index"]]["iteration"])
        oracle_iter = int(group[item["oracle_index"]]["iteration"])
        ax.axvline(0, color="#4c956c", linestyle=":", linewidth=1.1, label="baseline $M_0$")
        ax.axvline(proposal_iter, color="#b85c5c", linestyle="--", linewidth=1.1,
                   label="original proposal $t^*$")
        ax.axvline(oracle_iter, color="#7e57a2", linestyle="-.", linewidth=1.1,
                   label="oracle iteration")
        ax.scatter([proposal_iter], [mious[item["proposal_index"]]], color="#b85c5c", s=55, zorder=5)
        ax.scatter([oracle_iter], [mious[item["oracle_index"]]], color="#7e57a2", s=55, zorder=5)
        decision = "gate: fallback" if not item["gate_accepts"] else "gate: accept"
        ax.set_title(f"{benchmark}\n{item['obj_name']} | {decision}", fontsize=10)
        ax.set_xlabel("Candidate iteration")
        ax.set_ylabel("mIoU / normalized score")
        ax.set_xticks(iterations)
        ax.set_ylim(min(0.0, min(mious) - 0.05), 1.02)
        ax.grid(True, alpha=0.25, linewidth=0.6)
        ax.text(
            0.03, 0.04,
            "proposal " + r"$\Delta$" + f" mIoU = {item['proposal_delta']:+.3f}\n"
            f"oracle--proposal = {item['oracle_gap']:.3f}\n"
            f"margin = {item['margin']:.3g}",
            transform=ax.transAxes,
            ha="left", va="bottom", fontsize=8.5,
            bbox=dict(boxstyle="round,pad=0.28", facecolor="white", edgecolor="#c2c9ce", alpha=0.92),
        )
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=5, bbox_to_anchor=(0.5, 1.04), frameon=False)
    fig.suptitle("Representative candidate-selection instability", fontsize=13, y=1.10)
    save_figure(fig, "candidate_instability")


def draw_risk_coverage() -> None:
    path = ROOT / "results/multicriteria/risk_coverage_persam.csv"
    matcher_path = ROOT / "results/multicriteria/risk_coverage_matcher.csv"
    rows = read_csv_rows(path) + read_csv_rows(matcher_path)
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["generator"], row["benchmark"])].append(row)
    calibration_rows = [
        row
        for row in read_csv_rows(
            ROOT / "results/multicriteria/episode_split_calibration.csv"
        )
        if row["split"] != "calibration"
    ]
    panels = [
        ("FSS-1000", ["PerSAM-F-compatible", "Matcher"]),
        ("COCO-20i", ["PerSAM-F-compatible", "Matcher"]),
        ("Pascal-5i", ["PerSAM-F-compatible"]),
    ]
    colors = {"PerSAM-F-compatible": "#176b87", "Matcher": "#b85c5c"}
    styles = {"PerSAM-F-compatible": "-", "Matcher": "--"}
    labels = {"PerSAM-F-compatible": "PerSAM-F-compatible", "Matcher": "Matcher"}
    fig, axes = plt.subplots(1, 3, figsize=(15.0, 4.15), constrained_layout=True)
    for ax, (benchmark, generators) in zip(axes, panels):
        ax.axhline(0.40, color="#666666", linestyle=":", linewidth=1.2, zorder=1)
        for generator in generators:
            data = [
                row for row in grouped[(generator, benchmark)]
                if math.isfinite(float(row["threshold"]))
            ]
            data.sort(key=lambda row: float(row["coverage"]))
            x = [float(row["coverage"]) for row in data]
            y = [float(row["conditional_degradation_risk"]) for row in data]
            ax.plot(x, y, color=colors[generator], linestyle=styles[generator], linewidth=1.8,
                    label=labels[generator])
            default = next(row for row in data if int(row["is_default_tau"]) == 1)
            endpoint = next(row for row in data if int(row["is_original_endpoint"]) == 1)
            ax.scatter(float(default["coverage"]), float(default["conditional_degradation_risk"]),
                       color=colors[generator], edgecolor="white", linewidth=0.7, s=42, zorder=5)
            ax.scatter(float(endpoint["coverage"]), float(endpoint["conditional_degradation_risk"]),
                       facecolors="none", edgecolors=colors[generator], marker="s", linewidth=1.1, s=42, zorder=5)
        heldout = [row for row in calibration_rows if row["benchmark"] == benchmark]
        ax.scatter(
            [float(row["coverage"]) for row in heldout],
            [float(row["conditional_degradation_risk"]) for row in heldout],
            facecolors="#F2C14E",
            edgecolors="#3F3F3F",
            marker="D",
            linewidth=0.7,
            s=38,
            zorder=6,
        )
        ax.set_title(benchmark)
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xlabel("Accepted refinement coverage")
        ax.set_ylabel("Conditional degradation risk")
        ax.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
        ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
        ax.grid(True, alpha=0.25, linewidth=0.6)
    handles, labels_ = axes[0].get_legend_handles_labels()
    handles.extend(
        [
            Line2D(
                [0], [0], marker="D", color="none", markerfacecolor="#F2C14E",
                markeredgecolor="#3F3F3F", markeredgewidth=0.7, markersize=5.5,
                label="Held-out, calibration-selected threshold",
            ),
            Line2D(
                [0], [0], color="#666666", linestyle=":", linewidth=1.2,
                label="Target risk = 0.40",
            ),
        ]
    )
    labels_.extend(["Held-out, calibration-selected threshold", "Target risk = 0.40"])
    fig.legend(handles, labels_, loc="upper center", ncol=4, bbox_to_anchor=(0.5, 1.045), frameon=False)
    fig.suptitle("Selective risk--coverage under baseline-relative gating", fontsize=13, y=1.11)
    save_figure(fig, "risk_coverage_all_generators")


def main() -> None:
    setup_style()
    draw_candidate_instability()
    draw_risk_coverage()
    print(f"Generated empirical figures in: {OUT}")


if __name__ == "__main__":
    main()
